### ISSUE TITLE
Detection of US Military aircraft

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#164]
Ysurac:

I realize you are not in the US so this may not be important to you but thought I would let you know if you are not already aware.  

Apparently US military flights are not able to be correctly identified. My statistics page shows only 8 total military flights. Looking these up shows that military aircraft from France, Germany, Italy, and the UK are correctly identified. US military flights are not recorded for what they are. 

I live about 8 KM from an airport that has a substantial amount of military traffic every day but those flights don't seem to be flagged in the database.

Thanks again.

**Comment by Ysurac** [comment]
I use the ident of flight to identify is they are in a military airline. I'm not sure US flights send info like ident or coordinates. I don't know, for now, how to identify a flight as military without airline info.
If you see military flights with ident not flagged as military, I could look at these.

**Comment by szarka77** [comment]
Most US Military flights use Mode-S but some, like the capture below, are ADS-B.

Here is a capture from ModeSdeco2.  AE0216 is a US Air Force KC-10 callsign TEAM22. It shows up in VRS as military but FlightAirMap lists it as Unknown N/A N/A.

```
2016-04-05 11:59:45.179  INFO     8DAE0216586991AE99A76182F49D DF17 Type 11 ICAO: AE0216 CA 5 LAT 44.523 LON -70.055 NIC 8 ALTITUDE 20025 QBIT 1 GR 0 TS 0 CPR 0 TIMESTAMP 14598719851985
2016-04-05 11:59:45.994  INFO     8DAE021699148BABD00CA9550568 DF17 Type 19 ICAO: AE0216 CA 5 NUCR 2 GNSS -1000 VSRC 1 VR 128 TT 201.575 GS 375.293 GR 0 IC 0 SSC 0 IFR 0 TIMESTAMP 1459871985
2016-04-05 11:59:46.062  INFO     8DAE02162050504DCB2820C9C6C6 DF17 Type 4 ICAO: AE0216 CALLSIGN TEAM22 CAT 4 CAT2 0 CA 5 GR 0 TIMESTAMP 1459871986
2016-04-05 11:59:46.193  INFO     8DAE0216E8CC3C6D993C00164810 DF17 Type 29 ICAO: AE0216 CA 5 GR 0 MCP 111 MCPS 1 TTRK 217 TCAS 1 TAT 1 VMI 2 HDA 3 HMI 0 TCASRUN 0 TIMESTAMP 1459871986
2016-04-05 11:59:46.531  INFO     8DAE021699148BABD010A9FD8768 DF17 Type 19 ICAO: AE0216 CA 5 NUCR 2 GNSS -1000 VSRC 1 VR 192 TT 201.575 GS 375.293 GR 0 IC 0 SSC 0 IFR 0 TIMESTAMP 1459871986
2016-04-05 11:59:46.783  INFO     8DAE0216F800000000393C08B151 DF17 Type 31 ICAO: AE0216 CA 5 GR 0 HRD 1 BDS65 TIMESTAMP 1459871986
2016-04-05 11:59:46.928  INFO     8DAE021699148BABD808A8FC6569 DF17 Type 19 ICAO: AE0216 CA 5 NUCR 2 GNSS -975 VSRC 1 VR -64 TT 201.575 GS 375.293 GR 0 IC 0 SSC 0 IFR 0 TIMESTAMP 1459871986

```

**Comment by szarka77** [comment]
Here is a Modes-S capture from a US Air Force KC-135 ICAO AE04C9:

```
2016-04-05 12:56:21.287  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875381
2016-04-05 12:56:23.373  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875383
2016-04-05 12:56:25.896  INFO     028190A00121D7 DF0 ICAO: AE04C9 ALTITUDE 3200 MBIT 0 QBIT 0 GR 0 RI 3 CC 1 SL 4 TIMESTAMP 1459875385
2016-04-05 12:56:26.527  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875386
2016-04-05 12:56:27.446  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875387
2016-04-05 12:56:29.621  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875389
2016-04-05 12:56:30.029  INFO     028190A2013DCC DF0 ICAO: AE04C9 ALTITUDE 3300 MBIT 0 QBIT 0 GR 0 RI 3 CC 1 SL 4 TIMESTAMP 1459875390
2016-04-05 12:56:30.682  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875390
2016-04-05 12:56:30.793  INFO     8DAE04C920483231DB5820B330AF DF17 Type 4 ICAO: AE04C9 CALLSIGN RCH165 CAT 4 CAT2 0 CA 5 GR 0 TIMESTAMP 1459875390
2016-04-05 12:56:32.626  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875392
2016-04-05 12:56:34.670  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875394
2016-04-05 12:56:35.426  INFO     5DAE04C94AF3DD DF11 ICAO: AE04C9 CA 5 GR 0 TIMESTAMP 1459875395
```

**Comment by Ysurac** [comment]
OK
For the second one, callsign RCH165, the airline was set as not active in DB. I will commit the fix.
For the first one I need to makes changes... I will add data for each aircrafts, this need to make somes changes to DB, code,... Should be done tomorrow.

**Comment by szarka77** [comment]
Military flights with the same registration frequently change callsigns.  Would it be better to look at ICAO or registration for identification?

**Comment by Ysurac** [comment]
It's what I will add, a flag for each ICAO.

**Comment by szarka77** [comment]
Great.  Would it help you if I sent you a list of all the military aircraft I have seen? If so please let me know what format you would like it in.

**Comment by Ysurac** [comment]
No, I have all data available, only need to add them to database.
Thanks

**Comment by szarka77** [comment]
Unfortunately, US military flights are still not being detected on my system. Watching a USAF KC-10 on the map right now, callsign HOIST78, ICAO AE0236, but it does not get flagged as military.  The transponder is ADS-B not Mode-S with coordinates. Aircraft type NA/NA.

Perhaps I have not configured my database correctly?

**Comment by Ysurac** [comment]
You have to run *scripts/update_db.php*. If database is older than 15 days all fields will be populated.

If database is newer than 15 days and you want to force update, you have to run this under MySQL/MariaDB:

    DELETE FROM `config` WHERE `config`.`name` = 'last_update_db';

**Comment by szarka77** [comment]
I've been running the update_db.php every five minutes with cron but still not tabulating US or Canadian Military flights. There was a Canadian C-130 on my VRS site until just a moment ago but it is not recorded.  It was Modes-S transponder. My stats only show 1 military flight for the past five days.

Do you think this is my setup or something in the php scripts?

**Comment by Ysurac** [comment]
If DB is updated, this should work.

You could try to run this under MySQL/MariaDB:
     
      SELECT count(*) FROM `aircraft_modes` WHERE `type_flight` = 'military';

Result should a little under 19000.

**Comment by szarka77** [comment]
Running that query shows a count of 18872.

**Comment by Ysurac** [comment]
Stats should be fixed in latest commit.

**Comment by szarka77** [comment]
Applied that commit.  Now showing 4 military flights. Hopefully this will take care of the issue going forward.

Thanks.

**Comment by szarka77** [comment]
Two days later but still only reporting 6 military flights.  Something is still wrong. Database is updating every 5 minutes with cron job.

**Comment by me2tkt** [comment]
The German Air Force uses an "+" in the aircraft registration e.g. 54+07.
This leads to an error in the search syntax as the "+" is dropped somewhere.
Manually adding the "+" finds the aircraft registration.

![gaf_search](https://cloud.githubusercontent.com/assets/23280102/23333879/1dd7520e-fb94-11e6-8707-3ac535269c2c.jpg)
