### ISSUE TITLE
daemon-spotter Error

### ISSUE THREAD

**Issue by gugaua** [Ysurac/FlightAirMap#224]
I have a fresh install of FlightAirMap and I manually start daemon-spotter.php but get a lot of errors.
 Error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION FlightAirMap.ST_Within does not exist
---

www-data@kd56398:~/html/map/scripts$ php5 daemon-spotter.php
Connecting...
Connect to phpvmacars source (http://www.fscva.net/va2/action.php/acars/data)...
Connected!
SCAN MODE

**********\* New aircraft hex : 303031 ***********
Error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION FlightAirMap.ST_Within does not exist
Update last seen flights data...
---

www-data@kd56398:~/html/map/scripts$ php5 daemon-spotter.php
Connecting...
Connect to phpvmacars source (http://www.fscva.net/va2/action.php/acars/data)...
Connected!
SCAN MODE

**********\* New aircraft hex : 303031 ***********
Error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION FlightAirMap.ST_Within does not exist
Update last seen flights data...
----- No Airport near last coord. Latitude : 49.651455314948 - Longitude : 9.3551417554292 - MinDist : 50
www-data@kd56398:~/html/map/scripts$ php5 daemon-spotter.php
Connecting...
Connect to phpvmacars source (http://www.fscva.net/va2/action.php/acars/data)...
Connected!
SCAN MODE

**********\* New aircraft hex : 303031 ***********
Check if aircraft is already in DB... Already in DB.
DATA : hex : 303031 - ident : TLH0001 - ICAO : A380 - Departure Airport : EDDF - Arrival Airport : EDDM - Latitude : 48.525544708171 - Longitude : 10.513471989621 - waypoints :  - Altitude : 180 - Heading : 139 - Speed : 315 - Departure Airport Time : 17:26:00 - Arrival Airport time : 18:10:07 - Pilot : MrFussL   - Source name : FSCVA
\o/ Add TLH0001 from phpvmacars in Live DB : (Add to SBS archive : Error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION FlightAirMap.ST_Within does not exist
success)success
---- Deleting Live Spotter data Not updated since 2 hour... Done
Check if aircraft is already in DB... Already in DB.
DATA : hex : 303031 - ident : TLH0001 - ICAO : A380 - Departure Airport : EDDF - Arrival Airport : EDDM - Latitude : 48.525544708171 - Longitude : 10.513471989621 - waypoints :  - Altitude : 180 - Heading : 139 - Speed : 315 - Departure Airport Time : 17:26:00 - Arrival Airport time : 18:10:07 - Pilot : MrFussL   - Source name : FSCVA
\o/ Add TLH0001 from phpvmacars in Live DB : (Add to SBS archive : Error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION FlightAirMap.ST_Within does not exist
success)success
Check if aircraft is already in DB... Already in DB.
DATA : hex : 303031 - ident : TLH0001 - ICAO : A380 - Departure Airport : EDDF - Arrival Airport : EDDM - Latitude : 48.468565838894 - Longitude : 10.611619202552 - waypoints :  - Altitude : 180 - Heading : 94 - Speed : 321 - Departure Airport Time : 17:26:00 - Arrival Airport time : 18:10:07 - Pilot : MrFussL   - Source name : FSCVA
\o/ Add TLH0001 from phpvmacars in Live DB : (Add to SBS archive : Error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION FlightAirMap.ST_Within does not exist
success)success

Is there a trick to repair it?

**Comment by Ysurac** [comment]
What is the DB used ? MySQL, MariaDB or PostgreSQL ? and what is the version number ?
*ST_Within* is a function that is supported since MySQL 5.6.1n MariaDB 5.3.3 and in PostGIS with PostgreSQL. 

I will try to disable it if not supported.

**Comment by Ysurac** [comment]
This is now disable if table **countries** was not added during install now, in latest commit.

**Comment by gugaua** [comment]
I use debian 8 with default 5.5.52-0+deb8u1.

How do I need to install that countries will not be populated

I installed the following way.

git clone https://github.com/Ysurac/FlightAirMap
Then via WEBUI setup
after that I changed required/settings globalinstalled to "FALSE" and run "php5 populate_all.php"
after that I changed required/settings globalinstalled to "TRUE" and started "php5 daemon-spotter.php"


Another thing is that mysql is using a lot of resources 60% CPU after start daemon-spotter
here is one second in apache2

134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.0)  AppleWebKit/5331 (KHTML, like Gecko) Chrome/13.0.885.0 Safari/5331"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; U; U; PPC Mac OS X 10_5_8; en-US) AppleWebKit/5312 (KHTML, like Gecko) Version/4.0.3 Safari/5312"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7_2) AppleWebKit/5340 (KHTML, like Gecko) Chrome/13.0.872.0 Safari/5340"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0; .NET CLR 3.5.30729.35)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.1; en-US; rv:18.0) Gecko/20100101 Firefox/18.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_9; rv:26.0) Gecko/20100101 Firefox/26.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.0; en-US; rv:19.0) Gecko/20100101 Firefox/19.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.0; WOW64; Trident/4.0; .NET CLR 3.0.4506.250)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.0; WOW64; Trident/5.0; .NET CLR 2.0.50727.379)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; .NET CLR 2.0.50727.483)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; .NET CLR 2.0.50727.94)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.1)  AppleWebKit/5320 (KHTML, like Gecko) Chrome/15.0.868.0 Safari/5320"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; WOW64; Trident/4.0; .NET CLR 3.5.30729.74)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/7.0; .NET CLR 2.0.50727.474)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.1; en-US; rv:19.0) Gecko/20100101 Firefox/19.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.0)  AppleWebKit/5311 (KHTML, like Gecko) Chrome/14.0.835.0 Safari/5311"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.1)  AppleWebKit/5331 (KHTML, like Gecko) Chrome/13.0.843.0 Safari/5331"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.1; en-US; rv:17.0) Gecko/20100101 Firefox/17.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.1; en-US; rv:17.0) Gecko/20100101 Firefox/17.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/5.0; .NET CLR 3.5.30729.580)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; U; U; PPC Mac OS X 10_6_4; en-US) AppleWebKit/5341 (KHTML, like Gecko) Version/4.0.3 Safari/5341"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.1; en-US; rv:23.0) Gecko/20100101 Firefox/23.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Macintosh; U; U; Intel Mac OS X 10_7_0) AppleWebKit/5362 (KHTML, like Gecko) Chrome/13.0.806.0 Safari/5362"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.0; WOW64)  AppleWebKit/5342 (KHTML, like Gecko) Chrome/15.0.852.0 Safari/5342 OPR/16.0.128177"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; WOW64; Trident/6.0; .NET CLR 3.5.30729.358)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.0)  AppleWebKit/5340 (KHTML, like Gecko) Chrome/14.0.839.0 Safari/5340"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.0; WOW64; Trident/5.0; .NET CLR 2.0.50727.297)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.1; en-US; rv:18.0) Gecko/20100101 Firefox/18.0"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; WOW64; Trident/5.0; .NET CLR 3.0.4506.203)"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 5.1)  AppleWebKit/5352 (KHTML, like Gecko) Chrome/15.0.898.0 Safari/5352"
134.255.225.217 - - [20/Oct/2016:09:49:28 +0200] "GET /va2/action.php/acars/data HTTP/1.1" 200 970 "-" "Mozilla/5.0 (Windows NT 6.0; en-US; rv:27.0) Gecko/20100101 Firefox/27.0"
_


11026 mysql     20   0 1173352 150116   8304 S  64.0  7.2  74:55.88 mysqld

If two pilots do the same flight with the same flightnumber there will be only one shown see screenshot.
You can see a red line between Airport EDDF and my position that happend after the 2nd pilot started the same flight(only 1 plane was visible).
Is it possible to diffear plane data by pilot id and not flight number?
![unbenannt](https://cloud.githubusercontent.com/assets/18068098/19551510/c6d48f78-96ab-11e6-885e-0499575161b2.JPG)

By the way awesome work, its nice to see such a great work, thank a lot for sharing it :)

**Comment by Ysurac** [comment]
* MySQL 5.5 is too old to support countries, I need function that are only from 5.6.1.
* For Apache, there is too much request. What is the value of **$globalMinFetch** in *require/settings.php* ?
* 2 flights with the same flight number should not be possible... And 1 flight with 2 pilots should be possible. What is the source ?

**Comment by gugaua** [comment]
Do I only need to delete countries via mysql-client to make it work if I dont want to upgrade to 5.6?
I think I will just upgrade mysql to 5.6 which will make it possible to use all features.

Here is the Value of MinFetch 15 Sec.
// MINIMUM TIME BETWEEN UPDATES FOR HTTP SOURCES (in seconds)
$globalMinFetch = '15';

The source is on the same server "phpvms"
$globalSources = array(array('host' => 'http://mywebsite/action.php/acars/data','port' => '80','name' => '','format' => 'phpvmacars','sourcestats' => FALSE));

It would be nice if we can do the same flight with 2 pilots(pilot ids) for example group flight.

**Comment by Ysurac** [comment]
* Yes. If table **countries** no exist in DB it will not use it in latest commit. If table **countries** exist in DB, remove it to use mysql 5.5.
* Seems to be ok.Maybe it's because the problem with **countries**...
* It's difficult to identify a flight with phpvms. In latest commit I use flight number and pilot id.

**Comment by gugaua** [comment]
I did a fresh install and upgraded mysql to 5.6
I cannot see any traffic anymore on the map

I get only this output
www-data@kd56398:~/html/map/scripts$ php5 daemon-spotter.php
Connecting...
Connect to phpvmacars source (http://www.fscva.net/va2/action.php/acars/data)...
Connected!
SCAN MODE

*********** New aircraft hex : 303032 ***********

and nothing else is happening further and no traffic on map

**Comment by Ysurac** [comment]
Your source seems to send an empty result: http://www.fscva.net/va2/action.php/acars/data

**Comment by gugaua** [comment]
I discovered that when I start the daemon-spotter, the flights are disappearing until I kill it

**Comment by Ysurac** [comment]
True, I have a bug. I try to find it...

**Comment by Ysurac** [comment]
Fixed in latest commit.

**Comment by gugaua** [comment]
Because phpvms is not working well with mysql server 5.6 I decided to create an extra server for FlightAirMap.
I wanted to install the new database via WEBUI on remote server but I get the following error

[Thu Oct 20 20:53:18.287721 2016] [:error] [pid 4935] [client 1.2.3.4:58371] PHP Fatal error:  Call to a member function prepare() on null in xxx/install/class.create_db.php on line 19, referer: http://xxx/map/install/index.php?1351574133&next=database_create

**Comment by Ysurac** [comment]
It's because it can't connect to db.

**Comment by gugaua** [comment]
Okay now it is connected to DB flight will be shown but not 3D Map, there is only a white site
http://fscva.net/map/

**Comment by Ysurac** [comment]
The problem is that **$globalCenterLatitude** & **$globalCenterLongitude** is set to ''.
This is fixed in latest commit.

**Comment by gugaua** [comment]
Genius, IT WORKS thank you for the super fast response I am speechless 

Danke Sehr für die tolle Hilfe!!! :) :) :)

**Comment by gugaua** [comment]
I found another issue

if there is a value for
$globalAircraftSize = '';
dynamic plane movement does not work, like now

**Comment by gugaua** [comment]
daemon-spotter.php is using 100% cpu and 3D map does not show any planes anymore

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1841 www-data  20   0  279708  18796   8756 R  99.8  0.4   4:20.73 php5

**Comment by Ysurac** [comment]
* Dynamic should work, it's really stange...
* No idea for the 100% CPU. What is your CPU ?
* You have to use a **.** not a **,** (comma) for **$globalCenterLongitude**

**Comment by Ysurac** [comment]
I have the same problem with phpvms with the CPU, I check that.

**Comment by gugaua** [comment]
O yes, once I had a . and once a , I changed both to . and it works like a charm.

i7-3770 CPU @ 3.40GHz

**Comment by Ysurac** [comment]
CPU usage is fixed in latest commit.

**Comment by gugaua** [comment]
CPU usage is ok.


okay new work for you :)

1. if I zoom in and move the map, map stops moving.
2. If planes are near to each other, you will select both of them like now

![unbenannt2](https://cloud.githubusercontent.com/assets/18068098/19605334/c1db450c-97b9-11e6-828a-aba376c85a54.JPG)

**Comment by gugaua** [comment]
okay, I updated, now I get very silly data
http://www.fscva.net/va/action.php/acars/data

Plane movement does still not work

**Comment by Ysurac** [comment]
Movement is calculated using the value of **$globalMapRefresh**, but if this value is too short flights don't move. Try to increase it.
This part will be changed soon.

**Comment by gugaua** [comment]
Do you support Virtual Airlines Manager?
http://vam.fscva.net/vam/get_live_flights.php

**Comment by gugaua** [comment]
updating METAR...METAR are only updated every hours.

Metar are being release every 30 minutes but can only be updated every hour.

its like 00:20, 00:50. 01:20, 01:50...

**Comment by Ysurac** [comment]
* I don't support Virtual Airlines Manager for now, but I will to support if I can get live data somewhere.
* Maybe I will put it at 30 minutes if there is no problems with NOAA server.

**Comment by gugaua** [comment]
It seems that METAR is not updated at all.
I have no cronjob for update_db and did not run it since yesterday evening and I get this message
updating METAR...METAR are only updated every hours.

Thats an old METAR report:
METAREDDM 220020Z 21004KT 9999 FEW040 BKN075 05/04 Q1015 NOSIG
2016-10-22 00:20:00 Wind: South-Southwest (210°) 2.06 m/s - Visibility: > 10000 m - Temperature: 5 °C - Dew point: 4 °C - Humidity: 93.3% - Pressure: 1015 hPa


Is there an option to see aircrafts already on ground? they will appear shortly after takeoff



I set $globalMapRefresh to 30, but it is still not working(dynamic plane movement)

**Comment by bilkaPek** [comment]
Hello.
putting in `settings.php` a line 83 
change the value ( "0" zero)
```
// MINIMAL CHANGE TO PUT IN DB
$globalCoordMinChange = '0'; // minimal change since last message for latitude/longitude (limit write to DB)
```

**Comment by gugaua** [comment]
Okay line changed but no effect.

And airport information will open BUT it will take about 5 min to open

**Comment by bilkaPek** [comment]
the change is to see the aircraft on the ground
not for metar
what is your source for traffic (PHPVms) ?

**Comment by gugaua** [comment]
yes, phpvms

**Comment by Ysurac** [comment]
The error with NOTAM s not a problem. Only a bad formatted NOTAM.
True for **globalCoordMinChange**, if there is info from aircraft on ground you will see them.
For airport page you try latest commit. This can be better... or not...

**Comment by gugaua** [comment]
daemon spotter tells me
*********** New aircraft hex : 303033 ***********
but there is no further DATA until takeoff

phpvms shows me
and there is lat and lng

[{"id":"1","pilotid":"DFA0007","flightnum":"FSC0003","pilotname":"Gugs Auster","aircraft":"4","lat":"50.04469764387","lng":"8.5648204844018","heading":"159","alt":"372","gs":"0","depicao":"EDLP","depapt":"Paderborn Lippstadt Airport","arricao":"EDDF","arrapt":"Frankfurt am Main International","deptime":"12:26:13","timeremaining":"00:00","arrtime":"12:26:13","route":"","route_details":[],"distremain":"1","phasedetail":"Boarding","online":"","lastupdate":"2016-10-23 12:26:13","client":"CCFTracker Free","aircraftname":"B737-800","registration":"4","code":"DFA","firstname":"Gugs","lastname":"Auster","depname":"Paderborn Lippstadt Airport","deplat":"51.6141","deplng":"8.61632","arrname":"Frankfurt am Main International","arrlat":"50.0414","arrlng":"8.58006","distremaining":"1"},

I am on latest commit now, there was nothing to update

**Comment by Ysurac** [comment]
Commited now.
True, I don't add to DB data that are exactly the same. This is never the case for real flight, but often the case for VA. Need to find a way to add them without adding thousands of line in DB...

**Comment by Ysurac** [comment]
In latest commit I add data if **lastupdate** is not the same, so this should work when flight is on ground.

**Comment by gugaua** [comment]
latest comit killed the daemon 
PHP Parse error:  syntax error, unexpected '$data' (T_VARIABLE) in /var/www/map/scripts/daemon-spotter.php on line 391

**Comment by bilkaPek** [comment]
change to the line 371 in` daemon-spotter.php`
value 30 by 41


`    		    if (count($line) > 30 && $line[0] != 'callsign') {`

**Comment by gugaua** [comment]
done,
PHP Parse error:  syntax error, unexpected '$data' (T_VARIABLE) in /var/www/map/scripts/daemon-spotter.php on line 391

**Comment by Ysurac** [comment]
I forget a **;**, fixed in latest commit

**Comment by bilkaPek** [comment]
yes it is that it accounts the line
the value `30` to the `line 371`  `daemon-spotter.php` by default not corespont the schema to whazzup.txt

**Comment by Ysurac** [comment]
It's not a problem, I check if there is more than that.

**Comment by gugaua** [comment]
more than 2 hours passed, and I cannot update METAR 
updating METAR...METAR are only updated every hours.

is there something I can do for dynamic plane movement?

**Comment by Ysurac** [comment]
* What are the values in table **config** ?
* Not for now, I need to find why it's not moving.

**Comment by gugaua** [comment]
+----+----------------------+---------------------+
| id | name                 | value               |
+----+----------------------+---------------------+
|  1 | schema_version       | 26                  |
|  4 | last_update_tle      | 2016-10-21 14:30:35 |
|  6 | last_update_notam_db | 2016-10-23 09:55:32 |
|  7 | last_update_metar    | 2016-10-23 10:00:09 |
+----+----------------------+---------------------+

**Comment by Ysurac** [comment]
And what is your local time ?

**Comment by gugaua** [comment]
13:58

**Comment by gugaua** [comment]
the two buttons below "-" Plot your Location and Compass Mode are not doing anything
![unbenannt3](https://cloud.githubusercontent.com/assets/18068098/19626121/3ef5a034-992a-11e6-8127-60eeef85b9cf.JPG)

**Comment by Ysurac** [comment]
Update fixed in latest commit.
Plot and Compass should work on a tablet or smartphone for example. Not tested since a long time...

**Comment by gugaua** [comment]
In your commit I can see that you changed install/class.update_db.php
is that also working for scripts/update_db.php?

**Comment by Ysurac** [comment]
**update_db.php** use some functions of **class.update_db.php**

**Comment by gugaua** [comment]
okay now its updating great :)

**Comment by gugaua** [comment]
I want to do a cronjob every hour with update_db.php
Metar gets update every 30 min xx:20 and xx:50
If I start at 5:20 the update will finish and write in config table that it finished 05:25 because it took 5 min to update.
so I cannot update at every hour because if I try to update 6:20 only 55 min passed

**Comment by gugaua** [comment]
Cron is also telling me Script is already runnning... even if its not

**Comment by Ysurac** [comment]
METAR can now be updated every 20 minutes in latest commit.
I use a **ps ux** and check if **update_db.php** appear in the result. That should not put false positive.

**Comment by gugaua** [comment]
thanks a lot for METAR!! :) :) :)


I checked ps ux and there is nothing running called update_db.

I can start update_db manually but not via cron because of that error

**Comment by Ysurac** [comment]
What is your cronjob line ?

**Comment by gugaua** [comment]
22 * * * * /usr/bin/php5 /var/www/map/scripts/update_db.php >> /var/www/map/scripts/log 2>&1

**Comment by Ysurac** [comment]
Should work...
You can comment or delete beginning of **update_db.php** but if the script is running more than one time this can make big problems.

**Comment by gugaua** [comment]
Should work... I can send you output of "ps ux" there is nothing like update_db so I don´t know why this is a false positive

**Comment by Ysurac** [comment]
If you put a *echo $output;* under the *exec("ps ux",....* we will see if there is something strange in the log. Maybe your cron daemon make a process with the name of the cronjob ?

**Comment by gugaua** [comment]
Script is already runnning...PHP Notice:  Array to string conversion in /var/www/map/scripts/update_db.php on line 11

**Comment by gugaua** [comment]
`// Check if script is not already running... (dirty)
if (strtoupper(substr(PHP_OS, 0, 3)) != 'WIN') {
        exec("ps ux", $output, $result);
        echo $output;
        $j = 0;
        foreach ($output as $line) if(strpos($line, "update_db.php")) $j++;
        if ($j > 1) {
                echo "Script is already runnning...";
                die();
        }
}
`

**Comment by Ysurac** [comment]
**print_r($output);** instead of **echo $output;** Sorry.

**Comment by gugaua** [comment]
(
    [0] => USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
    [1] => www-data  2329  0.0  0.0  23524  5416 pts/1    S+   Okt22   0:00 bash
    [2] => www-data  4457  0.0  0.0  23268  5076 pts/2    S    Okt22   0:00 bash
    [3] => www-data 14627  0.0  0.4 329100 29456 ?        S    16:42   0:00 /usr/sbin/apache2 -k start
    [4] => www-data 17395  0.0  0.4 329044 26996 ?        S    16:45   0:00 /usr/sbin/apache2 -k start
    [5] => www-data 19575  0.0  0.4 329032 27008 ?        S    16:48   0:00 /usr/sbin/apache2 -k start
    [6] => www-data 19587  0.0  0.3 326676 18900 ?        S    16:48   0:00 /usr/sbin/apache2 -k start
    [7] => www-data 19590  0.0  0.3 328464 23856 ?        S    16:48   0:00 /usr/sbin/apache2 -k start
    [8] => www-data 20681  0.0  0.4 329040 26484 ?        S    16:49   0:00 /usr/sbin/apache2 -k start
    [9] => www-data 20692  0.0  0.4 328896 26448 ?        S    16:49   0:00 /usr/sbin/apache2 -k start
    [10] => www-data 20693  0.0  0.4 329040 26488 ?        S    16:49   0:00 /usr/sbin/apache2 -k start
    [11] => www-data 20767  0.0  0.4 329040 26524 ?        S    16:49   0:00 /usr/sbin/apache2 -k start
    [12] => www-data 22361  0.0  0.0  23296  4888 pts/3    S+   16:51   0:00 bash
    [13] => www-data 22669  0.0  0.0   4336   704 ?        Ss   16:52   0:00 /bin/sh -c /usr/bin/php5 /var/www/map/scripts/update_db.php >> /var/www/map/scripts/log 2>&1
    [14] => www-data 22670  0.0  0.3 272888 20548 ?        S    16:52   0:00 /usr/bin/php5 /var/www/map/scripts/update_db.php
    [15] => www-data 22672  0.0  0.0   4336   752 ?        S    16:52   0:00 sh -c ps ux
    [16] => www-data 22673  0.0  0.0  19100  2464 ?        R    16:52   0:00 ps ux
    [17] => www-data 28255  0.0  0.4 279292 26800 pts/2    S+   13:39   0:01 php5 daemon-spotter.php
)

**Comment by Ysurac** [comment]
OK it use sh to run cronjob.
Should be fixed in latest commit.

**Comment by gugaua** [comment]
confirming fix :)

**Comment by gugaua** [comment]
Do you support SBS-3

**Comment by Ysurac** [comment]
Not yet. It's bug #208 
I don't have a feed using SBS-3 to make test and support for now...

**Comment by Ysurac** [comment]
It's supported in latest commit now.
