### ISSUE TITLE
Image sources

### ISSUE THREAD

**Issue by roo2002** [Ysurac/FlightAirMap#284]
Firstly my map displays data from a whazzup file and does display images if a Registration is the callsign or the aircraft trigraph and type are available.

I'd like to display an image of the aircraft type if an  image is not found by other means.

Below is what I have currently but I can't seem to display any image I have in my customs sources folder?

I've even tried removing all other sources but my image is still not displayed.
It does display in a Web browser.

What am I doing wrong?

// *** Aircraft pics ***
//Retrieve Image from externals sources
$globalAircraftImageFetch = TRUE;
//Sources for Aircraft image
$globalAircraftImageSources = array('customsources','wikimedia','airportdata','deviantart','flickr','bing','jetphotos','planepictures','planespotters','ivaomtl');
// Custom source configuration {registration} will be replaced by aircraft
registration (exif get copyright from exif data for each pic)
$globalAircraftImageCustomSources = array('thumbnail' => 'http://roo.servebeer.com/jfs/map/images/jfs/B744KAL.jpg','original' => 'http://roo.servebeer.com/jfs/map/images/jfs/B744KAL.jpg','source_website' => 'https://www.roo.servebeer.com', 'source' => 'Roo', 'exif' => true);
// ************************

**Comment by Ysurac** [comment]
There is no copyright available by exif and copyright field is not defined in *$globalAircraftImageCustomSources*, it's why it was not working.
Should be working with latest commit.

**Comment by roo2002** [comment]
Thank you although I still can't seem to get the map to show an image from my customs ounces folder.
All the aircraft on the map are fictional flightsim aircraft.
If a user sets a fictional registration then a picture of the aircraft type they are flying is shown.

But if a user sets a fictional Trigraph (callsign) a picture is not shown.

Is it possible to show a picture of the aircraft type for a fictional airline as is done with a fictional registration?

**Comment by Ysurac** [comment]
callsign is not used, only aircraft icao is used for VA in fact.

**Comment by roo2002** [comment]
Thank you.
So in theory if I was flying a B744, had the picture B744.jpg in my custom sources folder and a picture was not found by any other sources, that picture should be displayed using similar to below?
http://roo.servebeer.com/jfs/map/images/jfs/{type}.jpg

**Comment by Ysurac** [comment]
Yes but {type} is not defined, it's {registration} (even if it's replaced by aircraft icao).
You have to use latest commit, before only registration was used.

**Comment by roo2002** [comment]
Thank you.
I'll give it a whirl once I get chance.

**Comment by Ysurac** [comment]
Should be fixed in latest commit.

**Comment by roo2002** [comment]
Thank you.
Latest commit now in use.
I'm still having issues showing pictures from a custom source based on aircraft type.

Does the below look correct?

// *** Aircraft pics ***
//Retrieve Image from externals sources
$globalAircraftImageFetch = TRUE;
//Sources for Aircraft image
$globalAircraftImageSources = array('wikimedia','airportdata','deviantart','flickr','bing','jetphotos','planepictures','planespotters','ivaomtl','customsources');
// Custom source configuration {registration} will be replaced by aircraft
registration (exif get copyright from exif data for each pic)
$globalAircraftImageCustomSources = array('thumbnail' => 'http://roo.servebeer.com/jfs/map2/images/jfs/{registration}.jpg','original' => 'http://roo.servebeer.com/jfs/map2/images/jfs/{registration}.jpg','source_website' => 'http://www.roo.servebeer.com', 'source' => 'Roo','exif' => true);
// ************************

**Comment by Ysurac** [comment]
Should work but customsources is used after all others sources. You should put it first or alone:

   $globalAircraftImageSources = array('customsources');

When you run *spotter-daemon.php* with **$globalDebug = TRUE** you should see debug info.

**Comment by roo2002** [comment]
Putting custom sources first worked.

All now working.
Thank you.
