### ISSUE TITLE
Changing Style/Layout

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#287]
Hey!

is it allowed to change the Style of your map? (Just basic layout of the Map so it looks more like flightradar or planefinder)

i would create a news css file and link it to the index page.. i could also change your css files but after every update things would be lost.

**Comment by Ysurac** [comment]
You can do what you want, it's under Apache License 2.0, it only require preservation of copyright and license notices.

If some changes are nice, you can submit them and I will add them.

**Comment by MrDalle** [comment]
ok cool! i will give it a shot and keep you up to date!

**Comment by MrDalle** [comment]
Where do you insert the .css files?
I made now a custom css filehopefully overding the "standard skin"

**Comment by Ysurac** [comment]
in header.php

**Comment by MrDalle** [comment]
any idea how i can override the "basic skin"? its only working if i delete the specific code in the standard .css files...

**Comment by Ysurac** [comment]
You need to include it after my CSS files.

**Comment by MrDalle** [comment]
i did?
![d866634622a943e84065205490d60c5f](https://cloud.githubusercontent.com/assets/7756672/24521200/9b816350-158b-11e7-9c13-76a242e7663b.png)

**Comment by Ysurac** [comment]
Maybe you don't replace all part of the css in your file, no idea.

**Comment by Bigben83** [comment]
Post your CSS so we can help diagnose the issue., Ive been going to update the CSS for some time to make it more responsive and modern. glad you have started :-)

**Comment by MrDalle** [comment]
Got it working by inserting the fscskin.css in line 357 <- header.php

@Bigben83 I will post my css as soon i can show of the "skin" 👍

**Comment by MrDalle** [comment]
Any idea on how to reorder the layout of .showdetails ?

<img width="1680" alt="bildschirmfoto 2017-04-01 um 16 17 56" src="https://cloud.githubusercontent.com/assets/7756672/24579787/11ede93e-16fc-11e7-9bd1-29f51f95acdc.png">

**Comment by Bigben83** [comment]
About the only way would be to use a use javascript
something like this
http://jsfiddle.net/2DUXF/

http://stackoverflow.com/questions/10088496/jquery-reorder-divs

**Comment by MrDalle** [comment]
yep looks like this is the only way.. i dont want to edit the original files so i can provide this as a "skin" for everybody..

**Comment by Bigben83** [comment]
Great cant wait to see your finished product :-)

**Comment by Ysurac** [comment]
I can add an **id** to each div. This should help a little.

**Comment by MrDalle** [comment]
That would be cool! So you can reorder all items or hide the nav bar etc..

**Comment by Ysurac** [comment]
should be done in latest commit

**Comment by Bigben83** [comment]
@MrDalle how is your styling going :-)

**Comment by MrDalle** [comment]
@Bigben83 Im at work for the next 5 days so no progress now. But you can check the progress if you create an account on fscloud.net I embadded the map in our Virtual Airline System for all Pilots.

BTW: ID´s are working great!

**Comment by MrDalle** [comment]
Just upadated the map and it seems that the .showdetails is a bit broken. Its not more showing the plane but displays the "aicraft detected"
<img width="412" alt="bildschirmfoto 2017-04-13 um 15 34 32" src="https://cloud.githubusercontent.com/assets/7756672/25006965/18427bf8-205f-11e7-8458-d540966b70f5.png">

**Comment by Ysurac** [comment]
fixed

**Comment by MrDalle** [comment]
if you visit a pilot page under map.fswire.net/pilot/**_pilotid_** it just shows an empty page. 
Something wrong on my side or is this on "purpose" ?

**Comment by MrDalle** [comment]
i installed your fix but the page is still empty..

Is it possible to hide the navbar when iframing it to other pages?

**Comment by MrDalle** [comment]
Any update on the specific pilot pages? That would be a great addition so i can get rid of our old phpvms plugins...

**Comment by Ysurac** [comment]
No. If you have latest version and it still fails, I need log info or PHP debug info because I can't reproduce this problem.

**Comment by MrDalle** [comment]
ok i will look into it whats wrong on my side. Very strange..

**Comment by Ysurac** [comment]
I don't say it's on your side, but I can't reproduce it. So I need some log info or you need to enable PHP debug info, there is maybe a wrong check somewhere or an entry that make SQL fails. No idea.

**Comment by MrDalle** [comment]
Ok no Problem thanks for your effort!
Is it possible to Insert a new/second source to display active atc ? We are planning an ATC event but I have to clue how to display the active ATC on map...

**Comment by Ysurac** [comment]
Yes it's possible. If the second source only have ATC in it, ATC from that source should be displayed.
I don't really like how I display ATC, I need to work on that...

**Comment by MrDalle** [comment]
How do i format the source? i would upload a file in the desired format on my FTP and link the source..

I made a git for the theme so feel free to check it out!
https://github.com/MrDalle/FlightAirMap-Skin

**Comment by Ysurac** [comment]
In whazzup (or vatsimtxt) format.

I will check it and add a variable for custom skin.

**Comment by MrDalle** [comment]
Since you last update i have to define the skin somewhere. Can you give me a hint?

**Comment by Ysurac** [comment]
In **install/index.php** (or **$globalCustomCSS** in *require/settings.php*), you can set the path of one CSS (all should be in one CSS). For example: */css/custom/mycustomcss.css*.
At least updates can be easier using that...

Why do you change a js ?

**Comment by MrDalle** [comment]
I removed the red direct line so you just have the follow one and the "leading" one. (setting the weight from 2 to 0)

**Comment by Ysurac** [comment]
I don't know if the direct line is needed, maybe I will remove it... The follow one is better.

Should work, at least with a **;** at the end of *$globalCustomCSS*. You should also put a */* at the beginning of the path or the complete URL of the CSS.

**Comment by MrDalle** [comment]
Yea or just give it a id if its possible so users can turn it on or off.

Ok i tried now several different configs but its not displaying the new .css
![unbenannt](https://cloud.githubusercontent.com/assets/7756672/25893871/e7e70c82-3579-11e7-9ced-805ef4fc76a7.PNG)

**Comment by Ysurac** [comment]
Fixed in latest commit. Sorry.

**Comment by MrDalle** [comment]
still no luck.. i overwrote the old header.php and its displaying the path also in install/index.php but no change in the skin...

**Comment by Ysurac** [comment]
Working for me.
Added **$globalCustomCSS = 'http://map.fswire.net/css/custom/style.css';** in *require/settings.php* and your skin is used.

**Comment by MrDalle** [comment]
hmm weird.. i will clean the server and upload all files again..

**Comment by Ysurac** [comment]
It's only a small change in **header.php** so if there is no errors in **require/settings.php** all should be ok.

**Comment by MrDalle** [comment]
Ok i updated the whole server from scratch but still no luck...
I attached my settings.php but it should be ok!....

**Comment by MrDalle** [comment]
Yes its working! Much easier now to apply custom css thanks!

Any idea why the map type is blank when entering with cleaned cahe and coockies?

**Comment by Ysurac** [comment]
Seems to be a problem with mapbox, check your mapbox id and token.

**Comment by MrDalle** [comment]
i dont think so.. its working if you change it manually back and forth. Its only on intial visit without coockies etc

**Comment by Ysurac** [comment]
It's the mapbox id, you seems to have a wrong one (the tileset doesn't exist) : 

https://c.tiles.mapbox.com/v4/examples.map-i86nkdio/4/11/6.png?access_token=pk.eyJ1IjoibXJkYWxsZSIsImEiOiJjaWp5eWZwbmUwMDRydzVrcG9vbmQwMHg4In0.PEYgaRBMZ1k5VJhAi2780A

It's working for all mapbox, but not default one. The default tileset settings are defined in your Mapbox account.

**Comment by MrDalle** [comment]
I just dont find it... can you explain where i have to set the default tileset?

**Comment by Ysurac** [comment]
In your mapbox account, you can define tilesets, choose or create one and use the **Map ID** as mapbox id like *mapbox.mapbox-terrain-v2*.

**Comment by MrDalle** [comment]
Working now! Thanks.. :-)

**Comment by MrDalle** [comment]
i updatet the map but when clicking options like enable flight route etc nothing happens.. the map reloads but lines are still there.

I usuallay downlaod the newest release, clean the server, uplaod all files again an overwrite the settings.php
Should i do a complete install or is it ok to use the "old" settings.php?

**Comment by Ysurac** [comment]
You can always keep the old settings.php
Should be fixed in latest commit. If you set **$globalRoute** in *require/settings.php* to **FALSE** it's disabled by default for new user.
